# Generated by Django 3.1.2 on 2020-11-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_contactos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactos',
            name='Telefono',
            field=models.CharField(max_length=10),
        ),
    ]
