# Generated by Django 3.1.2 on 2020-11-03 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_auto_20201102_2233'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contactos',
            new_name='formulario',
        ),
    ]
