# Generated by Django 3.1.2 on 2020-11-03 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_auto_20201102_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='Telefono',
            field=models.IntegerField(),
        ),
    ]
