# Generated by Django 3.1.2 on 2020-11-03 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Apellido', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('Telefono', models.IntegerField(max_length=50)),
                ('Mensaje', models.CharField(max_length=5000)),
            ],
        ),
    ]
